---
data:
  download_path: ../downloads
  static_variables: ["geopotential", "land_sea_mask", "soil_type"]
  static_tag: gls
  surface_variables: ["10m_u_component_of_wind", "10m_v_component_of_wind", "2m_temperature", "mean_sea_level_pressure"]
  atmo_variables: ["temperature", "u_component_of_wind", "v_component_of_wind", "specific_humidity", "geopotential"]
  pressures: [50, 100, 150, 200, 250, 300, 400, 500, 600, 700, 850, 925, 1000]
  times: [0, 6, 12, 18]
  year: 2023
  month: 1
  days: [1, 2, 3, 4, 5, 6, 7]
inference:
  model: "microsoft/aurora"
  checkpoint: "aurora-0.25-pretrained.ckpt"
  use_lora: false
  steps: 28
  variable: "2t"
